# Additive only.
# Put only brand-new binds here that do not replace Omarchy defaults.

# The key for the mirror/display toggle button is XF86Display
bindd = , XF86Display, Toggle display mirror, exec, ~/.local/bin/toggle-mirror.sh

# Custom app launcher on a non-default Omarchy combo.
bindd = SUPER ALT, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
