# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

unbind = SUPER SHIFT, G
bindd = SUPER SHIFT, G, Matrix, exec, omarchy-launch-webapp "https://matrix.tuwien.ac.at"

unbind = SUPER SHIFT, E
bindd = SUPER SHIFT, E, Email,exec, omarchy-launch-webapp "https://mail.tuwien.ac.at"

# New binds that Omarchy does not already own
bindd = , XF86Display, Toggle display mirror, exec, ~/.local/bin/toggle-mirror.sh
