# Personal input overrides loaded from ~/.config/hypr/input.conf

input {
  kb_layout = us, de
  kb_options = compose:caps,grp:alts_toggle

  repeat_rate = 50
  repeat_delay = 500

  touchpad {
    natural_scroll = true
    gesture = 3, horizontal, workspace
    scroll_factor = 0.5
  }
}