# Personal monitor overrides loaded from ~/.config/hypr/monitors.conf

env = GDK_SCALE,1

monitor = desc:Lenovo Group Limited P40w-20 V90D9WWE, preferred, auto, 1.666667
monitor = , preferred, auto, 1.333333